project:
  type: website
  output-dir: docs
  resources:                          # ‚Üê ADD THIS BLOCK
    - "courses/LP_101_Interactive.html"                   # tells Quarto to copy this folder to docs/

execute:
  dir: project

website:
  title: "riki's site"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: 02_articles.qmd
        text: articles & papers
      - href: 01_projects.qmd
        text: projects
      - href: essay/index_essay.html
        text: essays
      - href: cdb/index_cdb.html
        text: LLM's daily brief

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    #theme: default
    css: styles.css

render:
  - "*.qmd"                # keep your top-level pages
  - "cdb/*.qmd"            # render every brief inside /cdb
