project:
  type: website
  output-dir: docs

execute:
  dir: project

website:
  title: "riki's site"
  navbar:
    left:
      - href: index.qmd
        text: home
      - href: projects.qmd
        text: projects
      - href: articles.qmd
        text: articles & papers
      - href: cdb/index_cdb.html
        text: ChatGPT's daily brief

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo
    css: styles.css

render:
  - "*.qmd"                # keep your top-level pages
  - "cdb/*.qmd"            # render every brief inside /cdb
